//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHOPAOQUANEntities1 : DbContext
    {
        public SHOPAOQUANEntities1()
            : base("name=SHOPAOQUANEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<sale> sale { get; set; }
        public virtual DbSet<size> size { get; set; }
        public virtual DbSet<subCategory> subCategory { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
