//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;

    public class ApplicationDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        // Constructor to pass the connection string to the base DbContext
        public ApplicationDbContext() : base("SHOPAOQUAN")
        {
        }
    }
    public partial class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id_user { get; set; }
        [Required(ErrorMessage = "Email không hợp lệ!")]
        public string email { get; set; }
        public string name_user { get; set; }
        public string phonenumber { get; set; }
        public string pass { get; set; }

    }
}
